apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: webserver
    tier: backend
  annotations:
    version: latest
    release_date: 2018/11/29
    contact: tpps88206
spec:
  containers:
  - name: pod-demo
    image: tpps88206/docker-demo
    ports:
    - containerPort: 3000
  nodeSelector:
    hardware: high-memory
