apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
  - hosts:
    - micheh.com
    secretName: micheh-tls
  rules:
    - host: micheh.com
      http:
        paths:
        - path: /
          backend:
            serviceName: wordpress
            servicePort: 80
        - path: /*
          backend:
            serviceName: wordpress
            servicePort: 80
